import Head from "next/head";
import type { NextPage } from "next";
import useGetAllPosts from "src/hooks/useGetAllPosts";

//components
import BlogCard from "src/components/blogCard";

//styles
import styles from "../styles/Home.module.css";

interface PostsProps {
  map: any;
  id: string;
  slug: string;
  title: string;
  author: {
    name: string;
    avatar: {
      url: string;
    };
  };
  coverPhoto: {
    url: string;
  };
  datePublished: string;
}

const Home: NextPage = () => {
  const { data, loading, error } = useGetAllPosts();

  if (loading) {
    return <p>loading...</p>;
  }

  if (error) {
    console.error(error);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data?.posts?.map((post: PostsProps) => (
          <BlogCard
            key={post.id}
            slug={post.slug}
            title={post.title}
            authorName={post.author?.name}
            coverPhoto={post.coverPhoto?.url}
            datePublished={post.datePublished}
            authorAvatar={post.author?.avatar?.url}
          />
        ))}
      </main>
    </div>
  );
};

export default Home;
